# Environment variables needed:
# - BRIDGE_POLARIS_ACCESSTOKEN
# - BRIDGE_POLARIS_SERVERURL
# - BRIDGE_POLARIS_APPLICATION_NAME
# - BRIDGE_POLARIS_PROJECT_NAME
# - BRIDGECLI_LINUX64
# - BD_TOKEN
# - BD_URL

version: 0.2
phases:
  install:
    commands:
       - curl -fLsS -o bridge.zip $BRIDGECLI_LINUX64
       - unzip bridge.zip  
       - curl -LOk https://detect.synopsys.com/detect8.sh
       - chmod +x ./detect8.sh
  build:
    commands:
       - ./synopsys-bridge --verbose --stage polaris polaris.assessment.types=SAST
       - bash detect8.sh --blackduck.url=$BD_URL --blackduck.api.token=$BD_TOKEN
  post_build:
    commands:
      - echo Scan completed on `date`
