name: Synopsys Security Testing

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Synopsys Action
        uses: synopsys-sig/synopsys-action@v1.1.0
        with:
          polaris_serverUrl: ${{ secrets.BRIDGE_POLARIS_SERVERURL }}
          polaris_accessToken: ${{ secrets.BRIDGE_POLARIS_ACCESSTOKEN }}
          polaris_application_name: "FCBR"
          polaris_project_name: "insecure-bank"
          polaris_assessment_types: "SCA,SAST"
