name: Synopsys - Actions

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Synopsys Action
        uses: synopsys-sig/synopsys-action@v1.1.0
        with:
          polaris_serverUrl: ${{ secrets.BRIDGE_POLARIS_SERVERURL }}
          polaris_accessToken: ${{ secrets.BRIDGE_POLARIS_ACCESSTOKEN }}
          polaris_application_name: "FCBR"
          polaris_project_name: "insecure-bank"
          polaris_assessment_types: "SAST"
      
      - name: Run Synopsys Detect
        uses: synopsys-sig/detect-action@v0.3.0
        env:
          NODE_EXTRA_CA_CERTS: ${{ secrets.LOCAL_CA_CERT_PATH }}
        with:
            scan-mode: INTELLIGENT
            github-token: ${{ secrets.GITHUB_TOKEN }}
            detect-version: 7.9.0
            blackduck-url: ${{ secrets.BLACKDUCK_URL }}
            blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
