name: "Synopsys CLI"

on:
  workflow_dispatch

jobs:
  build:
    runs-on: Ubuntu-latest
    env:
      BRIDGE_POLARIS_SERVERURL: ${{ secrets.BRIDGE_POLARIS_SERVERURL }}
      BRIDGE_POLARIS_ACCESSTOKEN: ${{ secrets.BRIDGE_POLARIS_ACCESSTOKEN }}
      BRIDGE_POLARIS_APPLICATION_NAME: "FCBR" # github.event.repository.name
      BRIDGE_POLARIS_PROJECT_NAME: "insecure-bank"
      BRIDGECLI_LINUX64: ${{ secrets.BRIDGECLI_LINUX64 }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: microsoft
        cache: maven
        
    - name: Download Bridge CLI
      run: |
        curl -fLsS -o bridge.zip $BRIDGECLI_LINUX64 && unzip -qo -d $RUNNER_TEMP bridge.zip && rm -f bridge.zip
        
    - name: Polaris (SAST)
      run: |
        $RUNNER_TEMP/synopsys-bridge --verbose --stage polaris polaris.assessment.types=SAST
        
    - name: Black Duck (SCA)
      run: |
         - .$RUNNER_TEMP/synopsys-bridge --stage blackduck  blackduck.url=$BLACKDUCK_URL  blackduck.token=$BLACKDUCK_ACCESS_TOKEN blackduck.automation.fixpr=false

